// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using coach_bags_selenium.Data;

namespace coach_bags_selenium.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20200802010549_SplitBrand")]
    partial class SplitBrand
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("coach_bags_selenium.Data.Product", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnName("id")
                        .HasColumnType("text");

                    b.Property<string>("Brand")
                        .HasColumnName("brand")
                        .HasColumnType("text");

                    b.Property<int>("Category")
                        .HasColumnName("category")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnName("created_utc")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Image")
                        .HasColumnName("image")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastPostedUtc")
                        .HasColumnName("last_posted_utc")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("LastUpdatedUtc")
                        .HasColumnName("last_updated_utc")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Link")
                        .HasColumnName("link")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnName("name")
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnName("price")
                        .HasColumnType("numeric");

                    b.Property<decimal>("SalePrice")
                        .HasColumnName("sale_price")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Savings")
                        .HasColumnName("savings")
                        .HasColumnType("numeric");

                    b.HasKey("Id")
                        .HasName("pk_products");

                    b.ToTable("products");
                });
#pragma warning restore 612, 618
        }
    }
}
